# FROM node:20-alpine
# WORKDIR /app
# COPY package.json .
# RUN npm install --production
# COPY . .
# EXPOSE 80
# CMD ["node", "index.js"]

# Database Configuration
DB_HOST=books-rds.cux0w262wytu.us-east-1.rds.amazonaws.com
PORT=3306
DB_USER=admin
DB_PASSWORD=Cloud123
DB_NAME=mydb

# Server
APP_PORT=80
NODE_ENV=development

# JWT
JWT_SECRET=my_super_secret_key_123456789
JWT_EXPIRES_IN=7d
