FROM maven:3.9.9-amazoncorretto-11 AS builder

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn clean package -DskipTests


FROM amazoncorretto:11-alpine-jdk

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

# Database Configuration
ENV DB_HOST=books-rds.cux0w262wytu.us-east-1.rds.amazonaws.com
ENV PORT=3306
ENV DB_USER=admin
ENV DB_PASSWORD=your_password
ENV DB_NAME=booksapp

# JWT Configuration
ENV JWT_SECRET=my_super_secret_key_123456789
ENV JWT_EXPIRES_IN=7d

EXPOSE 8084

ENTRYPOINT ["java", "-jar", "app.jar"]
