name: Frontend CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------
      # Docker Hub Login
      # -----------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------
      # Build Frontend Image
      # -----------------------------
      - name: Build Frontend Image
        run: |
          docker build \
            -t kanavenavamshi/frontend:latest \
            ./client

      # -----------------------------
      # Push Frontend Image
      # -----------------------------
      - name: Push Frontend Image
        run: |
          docker push kanavenavamshi/frontend:latest

      # -----------------------------
      # AWS OIDC Authentication
      # -----------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364410975057:role/OIDC-12
          aws-region: us-east-1

      # -----------------------------
      # Verify AWS Authentication
      # -----------------------------
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      # -----------------------------
      # Configure EKS
      # -----------------------------
      - name: Configure EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name naresh

      # -----------------------------
      # Test EKS Connection
      # -----------------------------
      - name: Test EKS
        run: |
          kubectl get nodes

      # -----------------------------
      # Deploy Frontend
      # -----------------------------
      - name: Deploy Frontend
        run: |
          kubectl apply -f kubernetes-files/frontend-deploy-service.yml

      # -----------------------------
      # Update Image
      # -----------------------------
      - name: Update Frontend Image
        run: |
          kubectl set image deployment/frontend \
            frontend=kanavenavamshi/frontend:latest

      # -----------------------------
      # Wait for Deployment
      # -----------------------------
      - name: Wait for Frontend
        run: |
          kubectl rollout status deployment/frontend --timeout=180s

      # -----------------------------
      # Verify
      # -----------------------------
      - name: Verify Frontend Deployment
        run: |
          kubectl get deployment frontend
          kubectl get pods
          kubectl get services
